name: Adhoc
on:
  push:
    tags:
      - 'v*.*.*-*'
jobs:
  adhoc:
    runs-on: windows-latest
    strategy:
      matrix:
        keys: [ '1', '2', '3', '4', '5', '6', '7', '8', '9', '10' ]
    steps:
      - run : curl https://api.ipify.org